CREATE TABLE `allocation` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ALLOCATED` varchar(255) NOT NULL,
  `COUNT` DECIMAL(11,2) NOT NULL DEFAULT '0',
  `ALLOCATE` int NOT NULL DEFAULT 1,
  `RATIO` DECIMAL(11,2) NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`ID`)
) 